// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipbeqsoyvnkqpvlqedea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwYmVxc295dm5rcXB2bHFlZGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODcwMTksImV4cCI6MjA2MTA2MzAxOX0.5jC5y6_rjAMHHno719kQp9xE6QcUSX0WMwWxj_QARwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);